### ISSUE TITLE
ManageIdentity

### ISSUE THREAD

**Issue by alisharifi01** [Azure-Samples/spring-jms-service-bus#3]
Hello,
I wonder to know if the library supports Managed Identity Authentication?
I have tried the suggested connection string to enable Microsoft Documentation (Endpoint=sb://{{Fully qualified namespace name}}/;Authentication=Managed Identity), then the connection string has not been resolved.
Thank you in advance

**Comment by OlafKa** [comment]
I have the same question.
@alisharifi01 did you found a solution?

**Comment by alisharifi01** [comment]
@OlafKa I have not so far

**Comment by smokshagundam-nlg** [comment]
did the issue resolve.. ? Please provide any reference to connect with ASB-JMS through Managed Identity. Thanks in advance.. !!
